use std::fs;

use camino::Utf8Path;

use crate::zero_config;

pub fn run(root: &Utf8Path) -> miette::Result<()> {
    let path = root.join("stratum.config.jsonc");
    if path.exists() {
        return Err(miette::miette!("{} already exists", path));
    }
    let cfg = zero_config::infer(root);
    let rendered = render_jsonc(&cfg);
    fs::write(&path, rendered).map_err(|e| miette::miette!("Could not write {path}: {e}"))?;
    println!("Wrote {path}");
    Ok(())
}

fn render_jsonc(cfg: &stratum_config::Config) -> String {
    let mut s = String::new();
    s.push_str("// Generated by `stratum-lint init`. Edit me.\n");
    s.push_str("{\n  \"$schema\": \"https://stratum.dev/schema/v1.json\",\n");
    s.push_str(&format!("  \"version\": {},\n", cfg.version));
    s.push_str(&format!(
        "  \"project\": {{ \"root\": \"{}\" }},\n",
        cfg.project.root
    ));
    s.push_str("  \"layers\": [\n");
    for l in &cfg.layers {
        s.push_str(&format!(
            "    {{ \"id\": \"{}\", \"path\": \"{}\", \"depends_on\": [] }},\n",
            l.id, l.path
        ));
    }
    s.push_str("  ],\n  \"rules\": {\n");
    for (slug, rc) in &cfg.rules {
        s.push_str(&format!(
            "    \"{slug}\": {{ \"severity\": \"{}\" }},\n",
            rc.severity
        ));
    }
    s.push_str("  },\n  \"overrides\": []\n}\n");
    s
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn rendered_jsonc_round_trips_through_parser() {
        let cfg = stratum_config::Config {
            version: 1,
            project: stratum_config::ProjectConfig {
                root: "./src".into(),
                extends: None,
            },
            layers: vec![],
            rules: BTreeMap::new(),
            overrides: vec![],
        };
        let txt = render_jsonc(&cfg);
        let path = camino::Utf8PathBuf::from("inline");
        let parsed = stratum_config::parse_str(&path, &txt).unwrap();
        assert_eq!(parsed.version, 1);
    }
}
